version: '3.1'
services:
  bot:
    image: python:3.8-slim
    container_name: script
    environment:
      - AUTH_ELECTRICITYMAP=${AUTH_ELECTRICITYMAP}
      - TWEETER_BEARER_TOKEN=${TWEETER_BEARER_TOKEN}
      - TWEETER_CONSUMMER_KEY=${TWEETER_CONSUMMER_KEY}
      - TWEETER_CONSUMMER_SECRET=${TWEETER_CONSUMMER_SECRET}
      - TWEETER_ACCESS_TOKEN=${TWEETER_ACCESS_TOKEN}
      - TWEETER_ACCESS_TOKEN_SECRET=${TWEETER_ACCESS_TOKEN_SECRET}
    depends_on:
      - db      
    volumes:
      - ./:/app
    command: sh -c "cd /app && pip install -r requirements.txt && cd /app/scripts && python run.py"
  db:
    image: postgres:13.11
