version: '3.1'
services:
  bot:
    image: python:3.8-slim
    container_name: script
    env_file:
      - .env
    volumes:
      - ./:/app
    command: sh -c "cd /app/scripts && pip install -r requirements.txt && cd /app/scripts && python run.py"
    # command: "tail -f /dev/null"
