version: '3.1'
services:
  bot:
    image: python:3.8-slim
    environment:
      - AUTH_ELECTRICITYMAP=${AUTH_ELECTRICITYMAP}
      - TWEETER_BEARER_TOKEN=${TWEETER_BEARER_TOKEN}
      - TWEETER_CONSUMMER_KEY=${TWEETER_CONSUMMER_KEY}
      - TWEETER_CONSUMMER_SECRET=${TWEETER_CONSUMMER_SECRET}
      - TWEETER_ACCESS_TOKEN=${TWEETER_ACCESS_TOKEN}
      - TWEETER_ACCESS_TOKEN_SECRET=${TWEETER_ACCESS_TOKEN_SECRET}
    volumes:
      - ./:/app
    command: tail -f /dev/null